## Supplement 4: Classification

In [2]:
%matplotlib inline
import numpy as np
import pandas as pd
import random
import math as m


### 4.3 Programming Task: Song popularity prediction using Logistic regression
The datasets __train-songs.csv__ and __test-songs.csv__ contain audio properties of various tracks collected from the music streaming site Spotify.


The goal of the task is to train a logistic regression classifier that predicts if
a given track is popular or not.
The dataset consists of 9 columns.
The first 8 columns contain various audio properties
which are provided as input features to the model.
The last column contains the class labels given by 0(not popular) and 1(popular).

i\. Implement the loss function and its gradient for the logistic regression model.
 

In [14]:
train_link = r"C:\Users\Derin\Desktop\semester 1\Signal\HW\04-Supplement-Programming-Materials\train-songs.csv"
test_link  = r"C:\Users\Derin\Desktop\semester 1\Signal\HW\04-Supplement-Programming-Materials\test-songs.csv"

train=pd.read_csv(train_link)
test=pd.read_csv(test_link)
train_x=train.iloc[:, :8]
train_y=train.iloc[:, 8:]
test_x=test.iloc[:, :8]
test_y=test.iloc[:, 8:]


w=[]
for i in range(8):
    a=random.SystemRandom().uniform(0, 1)
    w.append(a)
w=np.array(w)

def h_w(x,w):
    k=[]
    
    for i in range(len(x)):
        o=0
        for j in range(len(w)):
          f=x.iloc[i,j]*w[j]
          o=o+f  
        n=1/(1+(np.exp(-o)))
       
        k.append(n)
            
            
    return k
def predict(arb):
    predict=[]
    for i in range(len(arb)):
        if arb[i] >=0.5:
            p=1.0
        else:
            p=0.0
        
        predict.append(p)
        
    return predict
        

def J(k,y):
    m=len(y)
    r=0
    for i in range(len(y)): 
        r=r+((-y.iloc[i])*np.log(k[i])+((1-y.iloc[i])*(np.log(k[i]))))

    mse=(-1/m)*r
    return mse

def Grad_J(x,y,w,hw):
    grad=[]    
    for j in range(len(w)):
        m=len(x)
        r=0
        for i in range(len(x)):
        
            r=r+((hw[i])-(y.iloc[i]))*(x.iloc[i,j])
        g=(1/m)*r
        grad.append(g)
    return grad

def g_Descent(Grad_J,i,a,tol=1e-3,max=100,**grad_args):
    
    w=np.array(i)
    w_h=[i]
    
    for j in range(max):
        gradient=Grad_J(train_x,train_y,w,h_w_results_train)
        gradient=np.array(gradient)
        w=w-(a*gradient)
        w_h.append(w)
        
        if np.linalg.norm(gradient)<tol:
            break
            
    return w, w_h,i
        
    
    
    
     
        
        
    

    



In [5]:
h_w_results_train=h_w(train_x,w)
predict(h_w_results_train)

[1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0

In [6]:
J(h_w_results_train,train_y)

popular    0.000548
dtype: float64

In [7]:
Grad_J(train_x,train_y,w,h_w_results_train)

[popular    0.273869
 dtype: float64,
 popular    2.553342
 dtype: float64,
 popular   -6.097597
 dtype: float64,
 popular    0.291914
 dtype: float64,
 popular    0.067577
 dtype: float64,
 popular    0.102892
 dtype: float64,
 popular    0.261066
 dtype: float64,
 popular    57.296589
 dtype: float64]

In [11]:
w

array([0.02251373, 0.83539115, 0.41896013, 0.21520923, 0.69856043,
       0.73101374, 0.40998361, 0.66789208])

In [12]:
g_Descent(Grad_J,w,a=0.1)

(array([[-2.71617882e+00, -1.90330140e+00, -2.31973242e+00,
         -2.52348332e+00, -2.04013212e+00, -2.00767881e+00,
         -2.32870894e+00, -2.07080047e+00],
        [-2.55109017e+01, -2.46980243e+01, -2.51144553e+01,
         -2.53182062e+01, -2.48348550e+01, -2.48024017e+01,
         -2.51234319e+01, -2.48655234e+01],
        [ 6.09984830e+01,  6.18113604e+01,  6.13949294e+01,
          6.11911785e+01,  6.16745297e+01,  6.17069830e+01,
          6.13859529e+01,  6.16438613e+01],
        [-2.89662366e+00, -2.08374624e+00, -2.50017726e+00,
         -2.70392816e+00, -2.22057697e+00, -2.18812366e+00,
         -2.50915378e+00, -2.25124532e+00],
        [-6.53254171e-01,  1.59623249e-01, -2.56807770e-01,
         -4.60558672e-01,  2.27925221e-02,  5.52458318e-02,
         -2.65784293e-01, -7.87582603e-03],
        [-1.00640977e+00, -1.93532350e-01, -6.09963369e-01,
         -8.13714271e-01, -3.30363077e-01, -2.97909767e-01,
         -6.18939892e-01, -3.61031425e-01],
        [-2.5881

In [13]:
w

array([0.02251373, 0.83539115, 0.41896013, 0.21520923, 0.69856043,
       0.73101374, 0.40998361, 0.66789208])

   ii\. Using the gradient descent algorithm, train the logistic regression model.
You may reuse/modify the gradient descent algorithm from the previous supplement.




In [ ]:
h_w_results_test=h_w(test_x,w)
h_w_results_test

In [ ]:
predict=predict(h_w_results_test)
predict_array=np.array(predict)

In [ ]:
J(h_w_results_test,test_y)


iii\. Using model predictions on __test-songs.csv__, build the confusion
matrix and subsequently calculate the precision, recall, and F1-score for a threshold of 0.4.


In [ ]:
from sklearn import metrics
from matplotlib import pyplot as plt

confusion_matrix = metrics.confusion_matrix(test_y, predict_array)

cm_display = metrics.ConfusionMatrixDisplay(confusion_matrix = confusion_matrix, display_labels = [False, True])

cm_display = metrics.ConfusionMatrixDisplay(confusion_matrix = confusion_matrix, display_labels = [False, True])

cm_display.plot()
plt.show()




In [ ]:
Precision = metrics.precision_score(test_y, predict_array)
Precision

In [ ]:
recall = metrics.recall_score(test_y, predict)
recall

In [ ]:
F1_score = metrics.f1_score(test_y, predict)
F1_score

iv\. Plot the ROC curve for the model and calculate the AUC metric of your model.


In [ ]:
import scikitplot as skplt
import matplotlib.pyplot as plt

test_y = # ground truth labels
y_probas = # predicted probabilities generated by sklearn classifier
skplt.metrics.plot_roc_curve(y_true, y_probas)
plt.show()


v\. Consider the simpler models given below.The input $\mathbf{x}$ in these models takes only 4 input features from the given dataset.

- Model A $~~~~~~~~~~~$   $\mathbf{x}$ = $[$ danceability, key, valence, tempo $]^\top$
- Model B $~~~~~~~~~~~$  $\mathbf{x}$ = $[$ danceability, loudness, acousticness, instrumentalness $]^\top$
- Model C $~~~~~~~~~~~$ $\mathbf{x}$ = $[$ key, liveness, valence, tempo $]^\top$

Train these models using your logistic regression implementation and determine the best performing model using the AUC metric.